name:                elevanagram-haskell
version:             0.1.0.0
github:              "halyngoc/elevanagram-haskell"
license:             MIT
author:              "Ha Ly"
maintainer:          "lyha@pdx.edu"
copyright:           "2020 Ha Ly"

extra-source-files:
- README.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/halyngoc/elevanagram-haskell#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src
  ghc-options:
    - -O2
  dependencies:
    - criterion
    - random

executables:
  elevanagram-haskell-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -O2
    dependencies:
    - elevanagram-haskell

tests:
  elevanagram-haskell-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - elevanagram-haskell
